# Generated by Django 4.2.9 on 2024-03-24 13:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_vacation_approved_vacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
