# Generated by Django 4.2.9 on 2024-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_role_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='salary',
            field=models.PositiveIntegerField(default=3600),
            preserve_default=False,
        ),
    ]
