# Generated by Django 4.2.9 on 2024-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_department_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='weekly_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacation_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Death', 'Death'), ('Birth', 'Birth')], max_length=100),
        ),
    ]
