# Generated by Django 4.2.9 on 2024-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_department_weekly_hours_alter_vacation_vacation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='salary_after_deduction',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
