# Generated by Django 4.2.9 on 2024-03-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_absence_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='excused',
            field=models.BooleanField(null=True),
        ),
    ]
