# Generated by Django 4.2.9 on 2024-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_absence_excused'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='include_experience_and_overtime',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='Keep active to deduct.'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='excused',
            field=models.BooleanField(default=False),
        ),
    ]
