# Generated by Django 4.2.9 on 2024-03-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_department_include_experience_and_overtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='include_experience_and_overtime',
            new_name='add_experience_and_overtime',
        ),
    ]
