# Generated by Django 4.2.9 on 2024-03-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_employee_additional_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hour_rate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
