# Generated by Django 4.2.9 on 2024-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_department_hour_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eligible_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
