# Generated by Django 4.2.9 on 2024-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_employee_eligible_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='Imgs/Profile_Pics'),
        ),
    ]
