# Generated by Django 4.2.9 on 2024-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_employee_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
