# Generated by Django 4.2.9 on 2024-04-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_absencechangerequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencechangerequests',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=25),
        ),
    ]
